MagicDish/MagicDishWebApplication/Controllers/RecipesController.cs
using Microsoft.AspNetCore.Mvc;
using BusinessLogic;
using BusinessLogic.Repository;
using Microsoft.AspNetCore.Http;


namespace MagicDishWebApplication.Controllers
{
    public class RecipesController : Controller
    {
        private readonly ILogger<RecipesController> _logger;
        private IRecipeRepository _recipeRepository;
        public RecipesController(ILogger<RecipesController> logger, IRecipeRepository recipeRepository )
        {
            _recipeRepository = recipeRepository;
            _logger = logger;
        }
        // GET: RecipesController
        public async Task<IActionResult> Index()
    
        
        {
            List<Recipe> recipes = await _recipeRepository.GetAsync();
            return View(recipes);
        }

        // GET: RecipesController/Details/5
        public async  Task<ActionResult> Details(int id)
        {
            List<Recipe> recipes = await _recipeRepository.GetAsync();
            return View(recipes.FirstOrDefault(r => r.Id == id));
        }

        // GET: RecipesController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RecipesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Recipe recipe)
        {
            List<Recipe> recipes = await _recipeRepository.GetAsync();
            if (!ModelState.IsValid)
            {
                return View(recipe);
            }

            try
            {
                recipes.Add(recipe);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: RecipesController/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            List<Recipe> recipes = await _recipeRepository.GetAsync();
            if (!recipes.Any(p => p.Id == id))
            {
                //return StatusCode(StatusCodes.Status500InternalServerError);

                return NotFound();

                //return BadRequest();
            }
            return View(recipes.Single(p => p.Id == id));
        }

        // POST: RecipesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Recipe recipe)
        {
            List<Recipe> recipes = await _recipeRepository.GetAsync();

            if (!ModelState.IsValid)
            {
                return View(recipe);
            }

            try
            {
                var existingRecipe = recipes.First(r => r.Id == recipe.Id);

                existingRecipe.Id = recipe.Id;
                existingRecipe.Name = recipe.Name;
                existingRecipe.CookingTimeInMinutes = recipe.CookingTimeInMinutes;
                existingRecipe.IsVegeterian = recipe.IsVegeterian;
                existingRecipe.Description = recipe.Description;

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: RecipesController/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            List<Recipe> recipes = await _recipeRepository.GetAsync();
            var existingRecipe = recipes.First(r => r.Id == id);
            return View(existingRecipe);
        }

        // POST: RecipesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id, Recipe recipe)
        {
            List<Recipe> recipes = await _recipeRepository.GetAsync();
            try
            {
                var existingRecipe = recipes.First(p => p.Id == id);
                recipes.Remove(existingRecipe);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MagicDish/MagicDishWebApplication/Controllers/RecipesTableController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MagicDishWebApplication.Data;
using MagicDishWebApplication.Models;

namespace MagicDishWebApplication.Controllers
{
    public class RecipesTableController : Controller
    {
        private readonly MagicDishWebApplicationContext _context;

        public RecipesTableController(MagicDishWebApplicationContext context)
        {
            _context = context;
        }

        // GET: RecipesModels
        public async Task<IActionResult> Index()
        {
            return _context.Recipes != null ?
                        View(await _context.Recipes.ToListAsync()) :
                        Problem("Entity set 'MagicDishWebApplicationContext.Recipes'  is null.");
        }

        // GET: RecipesModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Recipes == null)
            {
                return NotFound();
            }

            var recipesModel = await _context.Recipes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (recipesModel == null)
            {
                return NotFound();
            }

            return View(recipesModel);
        }

        // GET: RecipesModels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: RecipesModels/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,CookingTimeInMinutes,IsVegeterian,Description")] RecipesModel recipesModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(recipesModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(recipesModel);
        }

        // GET: RecipesModels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Recipes == null)
            {
                return NotFound();
            }

            var recipesModel = await _context.Recipes.FindAsync(id);
            if (recipesModel == null)
            {
                return NotFound();
            }
            return View(recipesModel);
        }

        // POST: RecipesModels/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,CookingTimeInMinutes,IsVegeterian,Description")] RecipesModel recipesModel)
        {
            if (id != recipesModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(recipesModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RecipesModelExists(recipesModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(recipesModel);
        }

        // GET: RecipesModels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Recipes == null)
            {
                return NotFound();
            }

            var recipesModel = await _context.Recipes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (recipesModel == null)
            {
                return NotFound();
            }

            return View(recipesModel);
        }

        // POST: RecipesModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Recipes == null)
            {
                return Problem("Entity set 'MagicDishWebApplicationContext.Recipes'  is null.");
            }
            var recipesModel = await _context.Recipes.FindAsync(id);
            if (recipesModel != null)
            {
                _context.Recipes.Remove(recipesModel);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RecipesModelExists(int id)
        {
            return (_context.Recipes?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

MagicDish/MagicDishWebApplication/Views/Recipes/Create.cshtml
@model BusinessLogic.Recipe

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Recipe</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CookingTimeInMinutes" class="control-label"></label>
                <input asp-for="CookingTimeInMinutes" class="form-control" />
                <span asp-validation-for="CookingTimeInMinutes" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsVegeterian" /> <label asp-for="IsVegeterian"></label>
                    @*@Html.DisplayNameFor(model => model.IsVegeterian)*@
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-success" asp-action="Index"><i class="bi bi-arrow-left"></i> Back to List </a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MagicDish/MagicDishWebApplication/Views/Recipes/Delete.cshtml
@model BusinessLogic.Recipe

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Recipe</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            <label asp-for="Ingredients[0].Product.Id"></label>
        </dt>
        <dd class = "col-sm-10">
            @Model.Ingredients[0].Product.Id
        </dd>
        <dt class = "col-sm-2">
            <label asp-for="Ingredients[0].Product.Name"></label>
        </dt>
        <dd class = "col-sm-10">
            @Model.Ingredients[0].Product.Name
        </dd>
        <dt class = "col-sm-2">
            <label asp-for="Ingredients[0].Product.ProductCategory"></label>
        </dt>
        <dd class = "col-sm-10">
            @Model.Ingredients[0].Product.ProductCategory
        </dd>
        <dt class = "col-sm-2">
            <label asp-for="Ingredients[0].Product.UnitOfMeasure"></label>
        </dt>
        <dd class = "col-sm-10">
            @Model.Ingredients[0].Product.UnitOfMeasure
        </dd>
        <dt class = "col-sm-2">
            <label asp-for="Ingredients[0].Quantity"></label>
        </dt>
        <dd class = "col-sm-10">
            @Model.Ingredients[0].Quantity
        </dd>
        <dd class = "col-sm-10">
        <div>
            Ingredients
		    </div>

            <table class="table table-bordered table-striped">
                <thead>
                <tr>
                   @* <th>
                        //id placeholder
                    </th>  *@                
                    <th>
                        <label asp-for="Ingredients[0].Product.Name" class="control-label"></label>
                    </th>
                    <th>
                        <label asp-for="Ingredients[0].Product.ProductCategory" class="control-label"></label>
                    </th>
                    <th>
                        <label asp-for="Ingredients[0].Product.UnitOfMeasure" class="control-label"></label>
                    </th>
                    <th>
                        <label asp-for="Ingredients[0].Quantity" class="control-label"></label>
                    </th>
                </tr>
                </thead>
                <tbody>
                @for (var i = 0; i < Model.Ingredients.Count; i++)
                {
                    <tr>
                        @*<td>
                            <input type="hidden" asp-for="Ingredients[i].Product.Id" class="form-control"/>
                        </td>*@
                        <td>
                            @Model.Ingredients[i].Product.Name
                            <input type="hidden" asp-for="Ingredients[i].Product.Name" class="form-control"/>
                        </td>
                        <td>
                            @Model.Ingredients[i].Product.ProductCategory
                            <input type="hidden" asp-for="Ingredients[i].Product.ProductCategory" class="form-control"/>
                        </td>
                        <td>
                            @Model.Ingredients[i].Product.UnitOfMeasure
                            <input type="hidden" asp-for="Ingredients[i].Product.UnitOfMeasure" class="form-control"/>
                        </td>
                        <td>
                            @Model.Ingredients[i].Quantity
                            <input type="hidden" asp-for="Ingredients[i].Quantity" class="form-control"/>
                        </td>
                        
                    </tr>
                }
                </tbody>
            </table>
            </dd>

    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> 
        <a class="btn btn-success" asp-action="Index"><i class="bi bi-arrow-left"></i> Back to List </a>
    </form>
</div>

MagicDish/MagicDishWebApplication/Views/Recipes/Details.cshtml
@model BusinessLogic.Recipe

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Recipe</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            <label asp-for="Id"></label>
        </dt>
        <dd class = "col-sm-10">
            @Model.Id
        </dd>
        <dt class = "col-sm-2">
            <label asp-for="Name"></label>
        </dt>
        <dd class = "col-sm-10">
            @Model.Name
        </dd>
        <dt class = "col-sm-2">
            <label asp-for="CookingTimeInMinutes"></label>
        </dt>
        <dd class = "col-sm-10">
            @Model.CookingTimeInMinutes
        </dd>
        <dt class = "col-sm-2">
            <label asp-for="IsVegeterian"></label>
        </dt>
        <dd class = "col-sm-10">
            @Model.IsVegeterian
        </dd>
        <dt class = "col-sm-2">
            <label asp-for="Description"></label>
        </dt>
        <dd class = "col-sm-10">
            @Model.Description
        </dd>
        <dd class=" = "col-sm-10">
        
        <div>
            Ingredients
		    </div>

            <table class="table table-bordered table-striped">
                <thead>
                <tr>
                   @* <th>
                        //id placeholder
                    </th>  *@                
                    <th>
                        <label asp-for="Ingredients[0].Product.Name" class="control-label"></label>
                    </th>
                    <th>
                        <label asp-for="Ingredients[0].Product.ProductCategory" class="control-label"></label>
                    </th>
                    <th>
                        <label asp-for="Ingredients[0].Product.UnitOfMeasure" class="control-label"></label>
                    </th>
                    <th>
                        <label asp-for="Ingredients[0].Quantity" class="control-label"></label>
                    </th>
                </tr>
                </thead>
                <tbody>
                @for (var i = 0; i < Model.Ingredients.Count; i++)
                {
                    <tr>
                        @*<td>
                            <input type="hidden" asp-for="Ingredients[i].Product.Id" class="form-control"/>
                        </td>*@
                        <td>
                            @Model.Ingredients[i].Product.Name
                            <input type="hidden" asp-for="Ingredients[i].Product.Name" class="form-control"/>
                        </td>
                        <td>
                            @Model.Ingredients[i].Product.ProductCategory
                            <input type="hidden" asp-for="Ingredients[i].Product.ProductCategory" class="form-control"/>
                        </td>
                        <td>
                            @Model.Ingredients[i].Product.UnitOfMeasure
                            <input type="hidden" asp-for="Ingredients[i].Product.UnitOfMeasure" class="form-control"/>
                        </td>
                        <td>
                            @Model.Ingredients[i].Quantity
                            <input type="hidden" asp-for="Ingredients[i].Quantity" class="form-control"/>
                        </td>
                        
                    </tr>
                }
                </tbody>
            </table>

        <dd/>
    </dl>
</div>
<div>
    <a class="btn btn-warning" @Html.ActionLink("Edit", "Edit", new { id = Model.Id})
    <a class="btn btn-success" asp-action="Index"><i class="bi bi-arrow-left"></i> Back to List </a>
</div>

MagicDish/MagicDishWebApplication/Views/Recipes/Edit - kopia.cshtml
@using BusinessLogic
@model BusinessLogic.Recipe

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Recipe</h4>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control"/>
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CookingTimeInMinutes" class="control-label"></label>
                <input asp-for="CookingTimeInMinutes" class="form-control"/>
                <span asp-validation-for="CookingTimeInMinutes" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsVegeterian"/> <label asp-for="IsVegeterian"></label>
                    @*@Html.DisplayNameFor(model => model.IsVegeterian)*@
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control"/>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>*@

            <div>
            Category List
		    </div>

            <table class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>
                        @*id placeholder*@
                    </th>
                    <th>
                        <label asp-for="Ingredients[0].Product.Name" class="control-label"></label>
                    </th>
                    <th>
                        <label asp-for="Ingredients[0].Product.ProductCategory" class="control-label"></label>
                    </th>
                    <th>
                        <label asp-for="Ingredients[0].Product.UnitOfMeasure" class="control-label"></label>
                    </th>
                    <th>
                        <label asp-for="Ingredients[0].Quantity" class="control-label"></label>
                    </th>
                </tr>
                </thead>
                <tbody>
                @for (var i = 0; i < Model.Ingredients.Count; i++)
                {
                    <tr>
                        <td>
                            <input type="hidden" asp-for="Ingredients[i].Product.Id" class="form-control"/>
                        </td>
                        <td>
                            @Model.Ingredients[i].Product.Name
                            <input type="hidden" asp-for="Ingredients[i].Product.Name" class="form-control"/>
                        </td>
                        <td>
                            @Model.Ingredients[i].Product.ProductCategory
                            <input type="hidden" asp-for="Ingredients[i].Product.ProductCategory" class="form-control"/>
                        </td>
                        <td>
                            @Model.Ingredients[i].Product.UnitOfMeasure
                            <input type="hidden" asp-for="Ingredients[i].Product.UnitOfMeasure" class="form-control"/>
                        </td>
                        <td>
                            @Model.Ingredients[i].Quantity
                            <input type="hidden" asp-for="Ingredients[i].Quantity" class="form-control"/>
                        </td>
                        <td>
                        <a asp-controller="Recipes" asp-action="Edit" asp-route-id="@Model.Id"
                        class="btn btn-primary mx-1"> <i class="bi bi-pencil-square"></i> Edit</a>
                        </td>
                    </tr>
                }
                </tbody>
            </table>

            <div class="form-group">
                <button type="submit" class="btn btn-primary" style="width:150px">Save</button>
            </div>

            @*<button type="submit" class="btn btn-primary" style="width:150px">Update</button>
		    <a asp-controller="Category" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back to List
		</a>*@
        </form>
    </div>
</div>

<div>
    <a class="btn btn-success" asp-action="Index"><i class="bi bi-arrow-left"></i> Back to List </a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MagicDish/MagicDishWebApplication/Views/Recipes/Edit.cshtml
@using BusinessLogic
@model BusinessLogic.Recipe

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Recipe</h4>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control"/>
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CookingTimeInMinutes" class="control-label"></label>
                <input asp-for="CookingTimeInMinutes" class="form-control"/>
                <span asp-validation-for="CookingTimeInMinutes" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsVegeterian"/> <label asp-for="IsVegeterian"></label>
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control"/>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>*@

            <div>
            Ingredients
		    </div>

            <table class="table table-bordered table-striped">
                <thead>
                <tr>
                    @*<th>
                        id placeholder
                    </th>  *@                
                    <th>
                        <label asp-for="Ingredients[0].Product.Name" class="control-label"></label>
                    </th>
                    <th>
                        <label asp-for="Ingredients[0].Product.ProductCategory" class="control-label"></label>
                    </th>
                    <th>
                        <label asp-for="Ingredients[0].Product.UnitOfMeasure" class="control-label"></label>
                    </th>
                    <th>
                        <label asp-for="Ingredients[0].Quantity" class="control-label"></label>
                    </th>
                </tr>
                </thead>
                <tbody>
                @for (var i = 0; i < Model.Ingredients.Count; i++)
                {
                    <tr>
                        @*<td>
                            <input type="hidden" asp-for="Ingredients[i].Product.Id" class="form-control"/>
                        </td>*@
                        <td>
                            @Model.Ingredients[i].Product.Name
                            <input type="hidden" asp-for="Ingredients[i].Product.Name" class="form-control"/>
                        </td>
                        <td>
                            @Model.Ingredients[i].Product.ProductCategory
                            <input type="hidden" asp-for="Ingredients[i].Product.ProductCategory" class="form-control"/>
                        </td>
                        <td>
                            @Model.Ingredients[i].Product.UnitOfMeasure
                            <input type="hidden" asp-for="Ingredients[i].Product.UnitOfMeasure" class="form-control"/>
                        </td>
                        <td>
                            @Model.Ingredients[i].Quantity
                            <input type="hidden" asp-for="Ingredients[i].Quantity" class="form-control"/>
                        </td>
                        <td>
                        <div class="w-75 btn-group" role="group">
                        <a asp-controller="RecipesTable" asp-action="Edit" asp-route-id="@Model.Id"
                        class="btn btn-primary mx-1"> <i class="bi bi-pencil-square"></i> Edit</a>
                        <a asp-controller="RecipesTable" asp-action="Delete" asp-route-id="@Model.Id"
                        class="btn btn-danger mx-1"> <i class="bi bi-trash-fill"></i> Delete</a>
					</div>
                        </td>
                    </tr>
                }
                </tbody>
            </table>

            <div class="form-group">
                <button type="submit" class="btn btn-primary" style="width:150px">Save</button>
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-success" asp-action="Index"><i class="bi bi-arrow-left"></i> Back to List </a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MagicDish/MagicDishWebApplication/Views/Recipes/Index.cshtml
@model IEnumerable<BusinessLogic.Recipe>

@{
    ViewData["Title"] = "Index";
}

<h1>Welcome to your recipes list.</h1>

<p>
    <a class="btn btn-primary" asp-action="Create"><i class="bi bi-plus-circle"></i> Add new recipe </a>
</p>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>
                <label asp-for="First().Id"></label>
            </th>
            <th>
                <label asp-for="First().Name"></label>
            </th>
            <th>
                <label asp-for="First().CookingTimeInMinutes"></label>
            </th>
            <th>
                <label asp-for="First().IsVegeterian"></label>
            </th>
            <th>
                <label asp-for="First().Description"></label>
            </th>
            <th>
                <label asp-for="First().Ingredients"></label>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var recipe in Model) {
        <tr>
            <td>
                @recipe.Id
            </td>
            <td>
                @recipe.Name
            </td>
            <td>
                @recipe.CookingTimeInMinutes
            </td>
            <td>
                @recipe.IsVegeterian
            </td>
            <td>
                @recipe.Description
            </td>
            <td>
                @*@recipe.Ingredients*@
                @foreach (var ingredient in recipe.Ingredients)
                {
                    
                        @ingredient.Product.Name @Html.Raw(" ")
                        @ingredient.Quantity @Html.Raw(" ")
                        @ingredient.Product.UnitOfMeasure
                        @Html.Raw("\n")
                        @Html.Raw(",")
                    
                }
            </td>

            <td>
                <div class="w-75 btn-group" role="group">
                        <a asp-controller="Recipes" asp-action="Edit" asp-route-id="@recipe.Id"
                        class="btn btn-primary mx-1"> <i class="bi bi-pencil-square"></i> Edit</a>
                        <a asp-controller="Recipes" asp-action="Details" asp-route-id="@recipe.Id"
                        class="btn btn-success mx-1"> <i class="bi bi-card-list"></i> Details</a>
                        <a asp-controller="Recipes" asp-action="Delete" asp-route-id="@recipe.Id"
                        class="btn btn-danger mx-1"> <i class="bi bi-trash-fill"></i> Delete</a>
					</div>
            </td>
        </tr>
}
    </tbody>
</table>