MagicDish/MagicDishWebApplication/Controllers/FoodRepoController.cs
using BusinessLogic;
using BusinessLogic.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace MagicDishWebApplication.Controllers
{
    public class FoodRepoController : Controller
    {

        private readonly ILogger<HomeController> _logger;
        private IProductQuantityRepository _repository;

        public FoodRepoController(ILogger<HomeController> logger, IProductQuantityRepository repository)
        {
            _logger = logger;
            _repository = repository;
        }

        // GET: FoodRepoController
        public async Task<IActionResult> Index()
        {
            List<ProductQuantity> products = await _repository.GetAsync();
            return View(products);
        }
        
        // GET: FoodRepoController/Details/5
        public async Task<IActionResult> Details(int id)
        {
            List<ProductQuantity> products = await _repository.GetAsync();
            return View(products.FirstOrDefault(p => p.Product.Id == id));
        }

        // GET: FoodRepoController/Create
        public async Task<IActionResult> Create()
        {
            return View();
        }

        // POST: FoodRepoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductQuantity product)
        {
            List<ProductQuantity> products = await _repository.GetAsync();

            if (!ModelState.IsValid)
            {
                return View(product);
            }

            try
            {
                products.Add(product);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: FoodRepoController/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            List<ProductQuantity> products = await _repository.GetAsync();

            if (!products.Any(p => p.Product.Id == id))
            {
                //return StatusCode(StatusCodes.Status500InternalServerError);

                return NotFound();

                //return BadRequest();
            }
            return View(products.Single(p => p.Product.Id == id));
        }

        // POST: FoodRepoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ProductQuantity productQuantity)
        {
            List<ProductQuantity> products = await _repository.GetAsync();

            if (!ModelState.IsValid)
            {
                return View(productQuantity);
            }

            try
            {
                var existingProduct = products.First(a => a.Product.Id == productQuantity.Product.Id);

                existingProduct.Product.Id = productQuantity.Product.Id;
                existingProduct.Product.Name = productQuantity.Product.Name;
                existingProduct.Product.ProductCategory = productQuantity.Product.ProductCategory;
                existingProduct.Product.UnitOfMeasure = productQuantity.Product.UnitOfMeasure;
                existingProduct.Quantity = productQuantity.Quantity;

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: FoodRepoController/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            List<ProductQuantity> products = await _repository.GetAsync();

            var existingProduct = products.First(p => p.Product.Id == id);
            return View(existingProduct);
        }

        // POST: FoodRepoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id, ProductQuantity product)
        {
            List<ProductQuantity> products = await _repository.GetAsync();

            try
            {
                var existingAlbum = products.First(p => p.Product.Id == id);
                products.Remove(existingAlbum);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

MagicDish/MagicDishWebApplication/Views/FoodRepo/Create.cshtml
@model BusinessLogic.ProductQuantity

@{
    ViewData["Title"] = "Create";
}

<h1>Add new Product</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Product.Id" class="control-label"></label>
                <input asp-for="Product.Id" class="form-control" />
                <span asp-validation-for="Product.Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product.Name" class="control-label"></label>
                <input asp-for="Product.Name" class="form-control" />
                <span asp-validation-for="Product.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product.ProductCategory" class="control-label"></label>
                <input asp-for="Product.ProductCategory" class="form-control" />
                <span asp-validation-for="Product.ProductCategory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product.UnitOfMeasure" class="control-label"></label>
                <input asp-for="Product.UnitOfMeasure" class="form-control" />
                <span asp-validation-for="Product.UnitOfMeasure" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-success" asp-action="Index"><i class="bi bi-arrow-left"></i> Back to List </a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MagicDish/MagicDishWebApplication/Views/FoodRepo/Delete.cshtml
@model BusinessLogic.ProductQuantity

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Album</h4>
    <hr />
    <partial name="Partials/_Details" model="@Model" />

    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> 
        <a class="btn btn-success" asp-action="Index"><i class="bi bi-arrow-left"></i> Back to List </a>
    </form>
</div>

MagicDish/MagicDishWebApplication/Views/FoodRepo/Details.cshtml
@model BusinessLogic.ProductQuantity

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Product</h4>
    <hr />
    <partial name="Partials/_Details" model="@Model" />
</div>
<div>
    <a class="btn btn-warning" @Html.ActionLink("Edit", "Edit", new { id = Model.Product.Id }) </a>
    <a class="btn btn-success" asp-action="Index"><i class="bi bi-arrow-left"></i> Back to List </a>
</div>

MagicDish/MagicDishWebApplication/Views/FoodRepo/Edit.cshtml
@model BusinessLogic.ProductQuantity

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @Html.HiddenFor(model =>model.Product.Id)

            <div class="form-group">
                <label asp-for="Product.Name" class="control-label"></label>
                <input asp-for="Product.Name" class="form-control"/>
                <span asp-validation-for="Product.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product.ProductCategory" class="control-label"></label>
                <input asp-for="Product.ProductCategory" class="form-control"/>
                <span asp-validation-for="Product.ProductCategory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product.UnitOfMeasure" class="control-label"></label>
                <input asp-for="Product.UnitOfMeasure" class="form-control"/>
                <span asp-validation-for="Product.UnitOfMeasure" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control"/>
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>


<div>
    <a class="btn btn-success" asp-action="Index"><i class="bi bi-arrow-left"></i> Back to List </a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MagicDish/MagicDishWebApplication/Views/FoodRepo/Index.cshtml
@model IEnumerable<BusinessLogic.ProductQuantity>


@{
    ViewData["Title"] = "Index";
}

<h1>Welcome to your RepositoryName</h1>
<br />


<p>
    <a class="btn btn-primary" asp-action="Create"><i class="bi bi-plus-circle"></i> Add product to your repository</a>
</p>
<br />
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            @*<th>
                <label asp-for="First().Product.Id"></label>
            </th>*@
            <th>
                <label asp-for="First().Product.Name"></label>
            </th>
            <th>
                <label asp-for="First().Product.ProductCategory"></label>
            </th>
            <th>
                <label asp-for="First().Quantity"></label>
            </th>
            <th>
                <label asp-for="First().Product.UnitOfMeasure"></label>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var product in Model) {
        <tr>
            @*<td>
                @product.Product.Id
            </td>*@
            <td>
                @product.Product.Name
            </td>
            <td>
                @product.Product.ProductCategory
            </td>
            <td>
                @product.Quantity
            </td>
            <td>
                @product.Product.UnitOfMeasure
            </td>
            <td>
               <div class="w-75 btn-group" role="group">
                        <a asp-controller="FoodRepo" asp-action="Edit" asp-route-id="@product.Product.Id"
                        class="btn btn-primary mx-1"> <i class="bi bi-pencil-square"></i> Edit</a>
                        <a asp-controller="FoodRepo" asp-action="Details" asp-route-id="@product.Product.Id"
                        class="btn btn-success mx-1"> <i class="bi bi-card-list"></i> Details</a>
                        <a asp-controller="FoodRepo" asp-action="Delete" asp-route-id="@product.Product.Id"
                        class="btn btn-danger mx-1"> <i class="bi bi-trash-fill"></i> Delete</a>
					</div>
            </td>
        </tr>
}
    </tbody>
</table>