MagicDish/MagicDishWebApplication/Controllers/AvailableProductsController.cs
using Microsoft.AspNetCore.Mvc;
using BusinessLogic;
using BusinessLogic.Repository;
using Microsoft.AspNetCore.Http;



namespace MagicDishWebApplication.Controllers;

public class AvailableProductsController : Controller
{
    private readonly ILogger<AvailableProductsController> _logger;
    private IProductRepository _repository;

    public AvailableProductsController(ILogger<AvailableProductsController> logger, IProductRepository repository)
    {
        _logger = logger;
        _repository = repository;
    }

    // GET: FoodRepoController
    public async Task<IActionResult> Index()
    {
        List<Product> products = await _repository.GetAsync();
        return View(products);
    }

    // GET: AvailableProductsController/Details/5
    public async Task<IActionResult> Details(int id)
    {
        List<Product> products = await _repository.GetAsync();
        return View(products.FirstOrDefault(p => p.Id == id));
    }

    // GET: AvailableProductsController/Create
    public async Task<IActionResult> Create()
    {
        return View();
    }

    // POST: AvailableProductsController/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(Product product)
    {
        List<Product> products = await _repository.GetAsync();

        if (!ModelState.IsValid)
        {
            return View(product);
        }

        try
        {
            products.Add(product);
            return RedirectToAction("Index");
        }
        catch
        {
            return View();
        }
    }

    // GET: AvailableProductsController/Edit/5
    public async Task<IActionResult> Edit(int id)
    {
        List<Product> products = await _repository.GetAsync();

        if (!products.Any(p => p.Id == id))
        {
            //return StatusCode(StatusCodes.Status500InternalServerError);

            return NotFound();

            //return BadRequest();
        }

        return View(products.Single(p => p.Id == id));
    }

    // POST: AvailableProductsController/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, Product product)
    {
        List<Product> products = await _repository.GetAsync();

        if (!ModelState.IsValid)
        {
            return View(product);
        }

        try
        {
            var existingProduct = products.First(a => a.Id == product.Id);

            existingProduct.Id = product.Id;
            existingProduct.Name = product.Name;
            existingProduct.ProductCategory = product.ProductCategory;
            existingProduct.UnitOfMeasure = product.UnitOfMeasure;

            return RedirectToAction("Index");
        }
        catch
        {
            return View();
        }
    }

    // GET: AvailableProductsController/Delete/5
    public async Task<IActionResult> Delete(int id)
    {
        List<Product> products = await _repository.GetAsync();

        var existingProduct = products.First(p => p.Id == id);
        return View(existingProduct);
    }

    // POST: AvailableProductsController/Delete/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(int id, Product product)
    {
        List<Product> products = await _repository.GetAsync();

        try
        {
            var existingProduct = products.First(p => p.Id == id);
            products.Remove(existingProduct);

            return RedirectToAction(nameof(Index));
        }
        catch
        {
            return View();
        }
    }
}

MagicDish/MagicDishWebApplication/Views/AvailableProducts/Create.cshtml
@model BusinessLogic.Product

@{
    ViewData["Title"] = "Create";
}

<h1>Add new Product</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductCategory" class="control-label"></label>
                <input asp-for="ProductCategory" class="form-control" />
                <span asp-validation-for="ProductCategory" class="text-danger"></span>
            </div>            

            @*<li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Separated link</a>
          </div>
        </li>*@


            <div class="form-group">
                <label asp-for="UnitOfMeasure" class="control-label"></label>
                <input asp-for="UnitOfMeasure" class="form-control" />
                <span asp-validation-for="UnitOfMeasure" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />  
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-success" asp-action="Index"><i class="bi bi-arrow-left"></i> Back to List </a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MagicDish/MagicDishWebApplication/Views/AvailableProducts/Delete.cshtml
@model BusinessLogic.Product

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Album</h4>
    <hr />
    <partial name="Partials/_Details" model="@Model" />

    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a class="btn btn-success" asp-action="Index"><i class="bi bi-arrow-left"></i> Back to List </a>
    </form>
</div>

MagicDish/MagicDishWebApplication/Views/AvailableProducts/Details.cshtml
@model BusinessLogic.Product

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Product</h4>
    <hr />
    <partial name="Partials/_Details" model="@Model" />
</div>
<div>
    @*<a class="btn btn-warning" @Html.ActionLink("Edit", "Edit", new { id = @Model.Id }) </a>*@
    <a class="btn btn-warning" @Html.ActionLink("Edit", "Edit", new { id = @Model.Id }) </a>
    <a class="btn btn-success" asp-action="Index"><i class="bi bi-arrow-left"></i> Back to List </a>
</div>

MagicDish/MagicDishWebApplication/Views/AvailableProducts/Edit.cshtml
@model BusinessLogic.Product

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductCategory" class="control-label"></label>
                <input asp-for="ProductCategory" class="form-control" />
                <span asp-validation-for="ProductCategory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UnitOfMeasure" class="control-label"></label>
                <input asp-for="UnitOfMeasure" class="form-control" />
                <span asp-validation-for="UnitOfMeasure" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-success" asp-action="Index"><i class="bi bi-arrow-left"></i> Back to List </a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MagicDish/MagicDishWebApplication/Views/AvailableProducts/Index.cshtml
@model IEnumerable<BusinessLogic.Product>

@{
    ViewData["Title"] = "Index";
}

<h1>Available Products</h1>
<br />

<p>
    <a class="btn btn-primary" asp-action="Create"><i class="bi bi-plus-circle"></i> Add new product to the database</a>
</p>
<br />
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            @*<th>
                <label asp-for="First().Id"></label>
            </th>*@
            <th>
                <label asp-for="First().Name"></label>
            </th>
            <th>
                <label asp-for="First().ProductCategory"></label>
            </th>
            <th>
                <label asp-for="First().UnitOfMeasure"></label>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var product in Model) {
        <tr>
            @*<td>
                @product.Id
            </td>*@
            <td>
                @product.Name
            </td>
            <td>
                @product.ProductCategory
            </td>
            <td>
                @product.UnitOfMeasure
            </td>
            <td>
               <div class="w-75 btn-group" role="group">
                        <a asp-controller="AvailableProducts" asp-action="Edit" asp-route-id="@product.Id"
                        class="btn btn-primary mx-1"> <i class="bi bi-pencil-square"></i> Edit</a>
                        <a asp-controller="AvailableProducts" asp-action="Details" asp-route-id="@product.Id"
                        class="btn btn-success mx-1"> <i class="bi bi-card-list"></i> Details</a>
                        <a asp-controller="AvailableProducts" asp-action="Delete" asp-route-id="@product.Id"
                        class="btn btn-danger mx-1"> <i class="bi bi-trash-fill"></i> Delete</a>
					</div>
            </td>
        </tr>
}
    </tbody>
</table>